/**
 * Closed vocabulary and canonical catalog for
 * `a2a.shared-state.observability/v1`.
 *
 * The catalog describes only synthetic aggregate parsing and projection. It
 * does not collect runtime state, authorize an operator, or bind an endpoint.
 */

function deepFreeze<T>(value: T): Readonly<T> {
  if (value !== null && typeof value === "object" && !Object.isFrozen(value)) {
    Object.freeze(value);
    for (const nested of Object.values(value)) {
      deepFreeze(nested);
    }
  }
  return value;
}

const requirements = [
  {
    area: "deployment-topology",
    requiredSignals: [
      "configured-grade",
      "effective-grade",
      "grade-defaulted",
      "serving",
      "expected-process-band",
      "ownership",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "readiness",
    requiredSignals: [
      "ready",
      "effective-grade",
      "readiness-reason-codes",
    ],
    publicVisibility: "public-readiness-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "adapter-lifecycle-ownership",
    requiredSignals: [
      "backend-class",
      "lifecycle",
      "durability",
      "writer-model",
      "ownership",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "clock-continuity-migration",
    requiredSignals: [
      "clock-safety",
      "clock-continuity",
      "migration-state",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "replay",
    requiredSignals: [
      "source",
      "durability",
      "continuity",
      "reset-risk",
      "epoch-age-band",
      "pressure-band",
      "reset-reason-code",
      "aggregate-outcomes",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "rate-limit",
    requiredSignals: [
      "source",
      "durability",
      "continuity",
      "reset-risk",
      "epoch-age-band",
      "pressure-band",
      "reset-reason-code",
      "window-band",
      "limit-band",
      "aggregate-outcomes",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "lease-claim",
    requiredSignals: [
      "pressure-band",
      "oldest-age-band",
      "active-count",
      "expiring-count",
      "stale-count",
      "renewal-failure-count",
      "fencing-rejection-count",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "idempotency",
    requiredSignals: [
      "retention-policy-class",
      "new-count",
      "replayed-count",
      "conflict-count",
      "unknown-count",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "outbox",
    requiredSignals: [
      "pressure-band",
      "oldest-age-band",
      "sequence-high-water-class",
      "lag-band",
      "backlog-state-counts",
      "duplicate-replay-count",
      "order-integrity",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
  {
    area: "claim-graph-projection",
    requiredSignals: [
      "projection-version-class",
      "source-high-water-class",
      "checkpoint-high-water-class",
      "lag-band",
      "oldest-age-band",
      "completeness",
      "failed-batch-count",
      "rollback-count",
    ],
    publicVisibility: "public-aggregate",
    operatorVisibility: "authorized-operator-aggregate",
  },
] as const;

export const SHARED_STATE_OBSERVABILITY_V1_VALUES = deepFreeze({
  version: "a2a.shared-state.observability/v1",
  storageContractVersion: "a2a.shared-state.storage/v1",
  healthDeclarationVersion: 1,
  kinds: {
    catalog: "SharedStateObservabilityCatalogV1",
    candidate: "SharedStateObservabilityCandidateV1",
    readiness: "SharedStatePublicReadinessProjectionV1",
    public: "SharedStatePublicObservabilityProjectionV1",
    operator: "SharedStateOperatorObservabilityProjectionV1",
  },
  runtimeIntegration: "not-implemented",
  healthDeclarationBinding: "pure-parser-only",
  routeBinding: "not-implemented",
  extensionPolicy: "forbidden",
  operatorAuthorization: "required-outside-pure-projector",
  visibilityClasses: [
    "public-readiness-aggregate",
    "public-aggregate",
    "authorized-operator-aggregate",
  ],
  availabilityStates: [
    "available",
    "unavailable",
    "not-applicable",
  ],
  unavailableReasonCodes: [
    "adapter-unavailable",
    "unsupported-topology",
    "unsafe-clock",
    "incomplete-migration",
    "lost-fence",
    "collection-failed",
  ],
  notApplicableReasonCodes: [
    "primitive-not-implemented",
    "grade-not-applicable",
  ],
  clockContinuityStates: [
    "reset",
    "preserved",
    "unknown",
  ],
  migrationProjectionStates: [
    "complete",
    "incomplete",
    "not-applicable",
  ],
  expectedProcessBands: [
    "one",
    "multiple",
  ],
  pressureBands: [
    "none",
    "low",
    "medium",
    "high",
    "critical",
    "unknown",
  ],
  ageBands: [
    "under-1m",
    "under-5m",
    "under-1h",
    "under-1d",
    "one-day-or-more",
    "unknown",
  ],
  lagBands: [
    "caught-up",
    "under-10",
    "under-100",
    "under-1000",
    "1000-or-more",
    "unknown",
  ],
  highWaterClasses: [
    "empty",
    "active-low",
    "active-medium",
    "active-high",
    "unknown",
  ],
  rateWindowBands: [
    "under-1m",
    "1m-to-under-5m",
    "5m-to-under-1h",
    "1h-or-more",
    "unknown",
  ],
  rateLimitBands: [
    "under-10",
    "10-to-under-100",
    "100-to-under-1000",
    "1000-or-more",
    "unknown",
  ],
  idempotencyRetentionPolicyClasses: [
    "registered-v1-mixed",
    "non-expiring-until-prune-proof",
    "unknown",
  ],
  graphProjectionVersionClasses: [
    "claim-graph-projection-v1",
    "not-implemented",
    "unknown",
  ],
  orderIntegrityStates: [
    "preserved",
    "violations-observed",
  ],
  countStates: [
    "zero",
    "reported",
    "suppressed",
  ],
  errorCodes: [
    "invalid_type",
    "invalid_value",
    "invalid_enum",
    "invalid_discriminant",
    "unknown_field",
    "unknown_catalog_version",
    "out_of_range",
    "duplicate_value",
    "forbidden_observability_field",
    "health_declaration_invalid",
    "health_observation_mismatch",
    "unsafe_aggregate_combination",
  ],
  limits: {
    maxAggregateCount: 1_000_000_000,
    maxReadinessReasonCodes: 12,
    publicAggregationFloor: 5,
    operatorAggregationFloor: 3,
  },
  suppression: {
    zeroCountsAreReportable: true,
    belowFloorValue: null,
    propagation: "entire-count-group",
    unavailableHasNoMetrics: true,
    notApplicableHasNoMetrics: true,
    exactAgeTimestampAndHighWaterForbidden: true,
  },
  requirements,
  forbidden: {
    identityHandling: "raw-hashed-and-pseudonymous-forbidden",
    freeFormText: "forbidden",
    arbitraryMapsLabelsAndExtensions: "forbidden",
    topKeyAndTopTaskLists: "forbidden",
    exactTimestampsAgesAndHighWaterValues: "forbidden",
    fieldNames: [
      "__proto__",
      "prototype",
      "constructor",
      "id",
      "ids",
      "taskId",
      "workerId",
      "providerId",
      "ownerId",
      "requesterId",
      "eventId",
      "receiptId",
      "attemptId",
      "nodeId",
      "edgeId",
      "streamKey",
      "bucketKey",
      "requester",
      "ip",
      "ipAddress",
      "nonce",
      "digest",
      "hash",
      "requesterHash",
      "identityHash",
      "pseudonym",
      "credential",
      "credentials",
      "secret",
      "password",
      "token",
      "authorization",
      "cookie",
      "header",
      "headers",
      "payload",
      "claimText",
      "claimContent",
      "graphContent",
      "sourceContent",
      "provenancePayload",
      "artifactPath",
      "worktreePath",
      "dbPath",
      "databasePath",
      "dsn",
      "reason",
      "message",
      "label",
      "labels",
      "map",
      "metadata",
      "extension",
      "extensions",
      "topKeys",
      "topTasks",
      "topWorkers",
      "byTask",
      "byWorker",
      "byProvider",
      "byOwner",
      "timestamp",
      "createdAt",
      "updatedAt",
      "observedAt",
      "expiresAt",
      "age",
      "ageSec",
      "epochAgeSec",
      "highWater",
      "sourceHighWater",
      "checkpointHighWater",
      "streamSequence",
    ],
  },
  catalog: {
    kind: "SharedStateObservabilityCatalogV1",
    catalogVersion: "a2a.shared-state.observability/v1",
    storageContractVersion: "a2a.shared-state.storage/v1",
    healthDeclarationVersion: 1,
    runtimeIntegration: "not-implemented",
    healthDeclarationBinding: "pure-parser-only",
    routeBinding: "not-implemented",
    extensionPolicy: "forbidden",
    operatorAuthorization: "required-outside-pure-projector",
    visibilityClasses: [
      "public-readiness-aggregate",
      "public-aggregate",
      "authorized-operator-aggregate",
    ],
    aggregation: {
      maximumCount: 1_000_000_000,
      publicFloor: 5,
      operatorFloor: 3,
      belowFloorValue: null,
      propagation: "entire-count-group",
    },
    absentSemantics: {
      unavailable: "reason-code-with-no-metrics",
      notApplicable: "reason-code-with-no-metrics",
      unknownBand: "observed-but-not-classifiable",
    },
    requirements,
    forbidden: {
      identityHandling: "raw-hashed-and-pseudonymous-forbidden",
      freeFormText: "forbidden",
      arbitraryMapsLabelsAndExtensions: "forbidden",
      topKeyAndTopTaskLists: "forbidden",
      exactTimestampsAgesAndHighWaterValues: "forbidden",
    },
  },
} as const);

export type SharedStateObservabilityV1Values =
  typeof SHARED_STATE_OBSERVABILITY_V1_VALUES;
