import {
  DECISION_DIALECTIC_KIND,
  DECISION_DIALECTIC_VERSION,
} from "./types.js";

const NonEmptyString = { type: "string", minLength: 1 } as const;
const Score01 = { type: "number", minimum: 0, maximum: 1 } as const;
const StringArray = { type: "array", items: NonEmptyString } as const;

const SharedDefs = {
  agentRef: {
    type: "object",
    additionalProperties: false,
    required: ["agentId"],
    properties: {
      agentId: NonEmptyString,
      sessionKey: NonEmptyString,
      nodeId: NonEmptyString,
      teamId: NonEmptyString,
      roleHint: NonEmptyString,
    },
  },
  vetoFlag: {
    type: "object",
    additionalProperties: false,
    required: ["code", "reason", "severity"],
    properties: {
      code: NonEmptyString,
      reason: NonEmptyString,
      severity: { type: "string", enum: ["warn", "blocker"] },
    },
  },
  verdict: {
    type: "string",
    enum: ["PROCEED", "PROCEED_WITH_GUARDRAILS", "WAIT", "ABSTAIN", "VETO"],
  },
  meta: {
    type: "object",
    additionalProperties: false,
    required: [
      "topic",
      "domain",
      "urgency",
      "openedAt",
      "snapshotAt",
      "expiresAt",
      "openedBy",
    ],
    properties: {
      topic: NonEmptyString,
      domain: NonEmptyString,
      urgency: { type: "string", enum: ["low", "normal", "high", "critical"] },
      openedAt: NonEmptyString,
      snapshotAt: NonEmptyString,
      expiresAt: NonEmptyString,
      openedBy: NonEmptyString,
      contextRefs: StringArray,
      tags: StringArray,
    },
  },
  context: {
    type: "object",
    additionalProperties: false,
    required: ["brief", "objective"],
    properties: {
      brief: NonEmptyString,
      objective: NonEmptyString,
      constraints: StringArray,
      decisionCriteria: StringArray,
      evidenceRefs: StringArray,
      availableTools: StringArray,
      hardVetoPolicy: StringArray,
      domainContext: { type: "object", additionalProperties: true },
    },
  },
  thesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "claim",
      "proposal",
      "rationale",
      "expectedBenefits",
      "evidenceRefs",
      "assumptions",
      "risks",
      "confidence",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      claim: NonEmptyString,
      proposal: NonEmptyString,
      rationale: NonEmptyString,
      expectedBenefits: StringArray,
      evidenceRefs: StringArray,
      assumptions: StringArray,
      risks: StringArray,
      confidence: Score01,
    },
  },
  antithesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "counterClaim",
      "whyThesisMayFail",
      "failureModes",
      "contradictions",
      "vetoFlags",
      "evidenceRefs",
      "confidence",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      counterClaim: NonEmptyString,
      whyThesisMayFail: NonEmptyString,
      failureModes: StringArray,
      contradictions: StringArray,
      vetoFlags: { type: "array", items: { $ref: "#/$defs/vetoFlag" } },
      evidenceRefs: StringArray,
      confidence: Score01,
    },
  },
  rebuttal: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "response",
      "defendedClaims",
      "concededRisks",
      "residualRisks",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      response: NonEmptyString,
      defendedClaims: StringArray,
      concededRisks: StringArray,
      residualRisks: StringArray,
    },
  },
  synthesis: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "submittedAt",
      "preserve",
      "discard",
      "decisionRule",
      "verdict",
      "guardrails",
      "followups",
      "unresolved",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      preserve: StringArray,
      discard: StringArray,
      decisionRule: NonEmptyString,
      verdict: { $ref: "#/$defs/verdict" },
      guardrails: StringArray,
      followups: StringArray,
      unresolved: StringArray,
    },
  },
  decision: {
    type: "object",
    additionalProperties: false,
    required: [
      "action",
      "routeTo",
      "ttlSec",
      "hardVeto",
      "decisionPolicyRef",
      "decisionBasisRevision",
    ],
    properties: {
      action: { $ref: "#/$defs/verdict" },
      routeTo: NonEmptyString,
      ttlSec: { type: "integer", minimum: 0 },
      hardVeto: { type: "boolean" },
      decisionPolicyRef: NonEmptyString,
      decisionBasisRevision: { type: "integer", minimum: 0 },
    },
  },
  outcome: {
    type: "object",
    additionalProperties: false,
    required: [
      "author",
      "observedAt",
      "implemented",
      "outcomeSummary",
      "notes",
      "decisionBasisRevision",
    ],
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      observedAt: NonEmptyString,
      implemented: { type: "boolean" },
      outcomeSummary: NonEmptyString,
      impactScore: Score01,
      thesisScore: Score01,
      antithesisScore: Score01,
      synthesisScore: Score01,
      notes: NonEmptyString,
      decisionBasisRevision: { type: "integer", minimum: 0 },
    },
  },
} as const;

export const DecisionDialecticTaskJsonSchema = {
  $id: "decisionDialectic.task.v1",
  type: "object",
  additionalProperties: false,
  required: ["kind", "version", "taskId", "revision", "state", "meta", "roles", "context"],
  $defs: SharedDefs,
  properties: {
    kind: { const: DECISION_DIALECTIC_KIND },
    version: { const: DECISION_DIALECTIC_VERSION },
    taskId: NonEmptyString,
    revision: { type: "integer", minimum: 0 },
    state: {
      type: "string",
      enum: [
        "OPEN",
        "THESIS_SUBMITTED",
        "ANTITHESIS_SUBMITTED",
        "REBUTTAL_SUBMITTED",
        "WAITING",
        "DECISION_ROUTED",
        "ABSTAINED",
        "VETOED",
        "SETTLED",
        "EXPIRED",
        "CANCELLED",
        "FAILED",
      ],
    },
    meta: { $ref: "#/$defs/meta" },
    roles: {
      type: "object",
      additionalProperties: false,
      required: ["thesisAgent", "antithesisAgent", "synthAgent"],
      properties: {
        thesisAgent: { $ref: "#/$defs/agentRef" },
        antithesisAgent: { $ref: "#/$defs/agentRef" },
        rebuttalAgent: { $ref: "#/$defs/agentRef" },
        synthAgent: { $ref: "#/$defs/agentRef" },
      },
    },
    context: { $ref: "#/$defs/context" },
    thesis: { $ref: "#/$defs/thesis" },
    antithesis: { $ref: "#/$defs/antithesis" },
    rebuttal: { $ref: "#/$defs/rebuttal" },
    synthesis: { $ref: "#/$defs/synthesis" },
    decision: { $ref: "#/$defs/decision" },
    outcome: { $ref: "#/$defs/outcome" },
  },
} as const;

export const DecisionDialecticTaskInputJsonSchema = {
  $id: "decisionDialectic.taskInput.v1",
  type: "object",
  additionalProperties: false,
  required: ["contract"],
  properties: {
    contract: {
      type: "object",
      additionalProperties: false,
      required: ["kind", "version", "phase", "task"],
      properties: {
        kind: { const: DECISION_DIALECTIC_KIND },
        version: { const: DECISION_DIALECTIC_VERSION },
        phase: {
          type: "string",
          enum: ["thesis", "antithesis", "rebuttal", "synthesis", "outcome"],
        },
        task: DecisionDialecticTaskJsonSchema,
      },
    },
  },
} as const;

export const DecisionDialecticExpectedOutputJsonSchemas = {
  "decisionDialectic.thesis.v1": {
    $id: "decisionDialectic.thesis.v1",
    $defs: SharedDefs,
    ...SharedDefs.thesis,
  },
  "decisionDialectic.antithesis.v1": {
    $id: "decisionDialectic.antithesis.v1",
    $defs: SharedDefs,
    ...SharedDefs.antithesis,
  },
  "decisionDialectic.rebuttal.v1": {
    $id: "decisionDialectic.rebuttal.v1",
    $defs: SharedDefs,
    ...SharedDefs.rebuttal,
  },
  "decisionDialectic.synthesisDecision.v1": {
    $id: "decisionDialectic.synthesisDecision.v1",
    type: "object",
    additionalProperties: false,
    required: ["author", "submittedAt", "synthesis", "decision"],
    $defs: SharedDefs,
    properties: {
      author: { $ref: "#/$defs/agentRef" },
      submittedAt: NonEmptyString,
      synthesis: { $ref: "#/$defs/synthesis" },
      decision: { $ref: "#/$defs/decision" },
    },
  },
  "decisionDialectic.outcome.v1": {
    $id: "decisionDialectic.outcome.v1",
    $defs: SharedDefs,
    ...SharedDefs.outcome,
  },
} as const;
